app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods:  GET
app_publication:
    resource: "@AppBundle/Resources/config/routing/publication.yml"
    prefix:   /publication
app_localisation:
    resource: "@AppBundle/Resources/config/routing/localisation.yml"
    prefix:   /city
app_category:
    resource: "@AppBundle/Resources/config/routing/category.yml"
    prefix:   /category




